# Generated by Django 5.1.2 on 2024-10-17 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictedStockPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('predicted_close_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('predicted_open_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('predicted_high_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('predicted_low_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('predicted_volume', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
